stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker-compose up -d

test:
  stage: test
  script:
    - curl http://localhost/dvwa/setup.php || exit 1

deploy:
  stage: deploy
  script:
    - echo "Deploying DVWA..."